using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class ImitateShareDisplayPage : Page
{
	private RectTransform _placeHolder;
	protected RectTransform PlaceHolder
	{
		get
		{
			if(_placeHolder == null)
			{
				var t = ElementUtils.FindByPath(transform, "Content/$placeHolder");
				_placeHolder = t.GetComponent<RectTransform>();
			}
			return _placeHolder;
		}
	}

	private RawImage _rawImage_preview;
	protected RawImage RawImage_preview
	{
		get
		{
			if(_rawImage_preview == null)
			{
				var t = ElementUtils.FindByPath(transform, "Content/$placeHolder/$rawImage_preview");
				_rawImage_preview = t.GetComponent<RawImage>();
			}
			return _rawImage_preview;
		}
	}

}
