using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class ImitateResultPage : Page
{
	private Image _button_detailTab;
	protected Image Button_detailTab
	{
		get
		{
			if(_button_detailTab == null)
			{
				var t = ElementUtils.FindByPath(transform, "$button_detailTab");
				_button_detailTab = t.GetComponent<Image>();
			}
			return _button_detailTab;
		}
	}

	private Image _button_scoreTab;
	protected Image Button_scoreTab
	{
		get
		{
			if(_button_scoreTab == null)
			{
				var t = ElementUtils.FindByPath(transform, "$button_scoreTab");
				_button_scoreTab = t.GetComponent<Image>();
			}
			return _button_scoreTab;
		}
	}

	private RectTransform _previewRectHolder;
	protected RectTransform PreviewRectHolder
	{
		get
		{
			if(_previewRectHolder == null)
			{
				var t = ElementUtils.FindByPath(transform, "Image_frame/mask/$previewRectHolder");
				_previewRectHolder = t.GetComponent<RectTransform>();
			}
			return _previewRectHolder;
		}
	}

	private RawImage _rawImage_preview;
	protected RawImage RawImage_preview
	{
		get
		{
			if(_rawImage_preview == null)
			{
				var t = ElementUtils.FindByPath(transform, "Image_frame/mask/$rawImage_preview");
				_rawImage_preview = t.GetComponent<RawImage>();
			}
			return _rawImage_preview;
		}
	}

	private RectTransform _tab_score;
	protected RectTransform Tab_score
	{
		get
		{
			if(_tab_score == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score");
				_tab_score = t.GetComponent<RectTransform>();
			}
			return _tab_score;
		}
	}

	private Text _text_score;
	protected Text Text_score
	{
		get
		{
			if(_text_score == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/Image_likely/$text_score");
				_text_score = t.GetComponent<Text>();
			}
			return _text_score;
		}
	}

	private Image _imitateButton_nextLevel;
	protected Image ImitateButton_nextLevel
	{
		get
		{
			if(_imitateButton_nextLevel == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/$ImitateButton_nextLevel");
				_imitateButton_nextLevel = t.GetComponent<Image>();
			}
			return _imitateButton_nextLevel;
		}
	}

	private Image _imitateButton_restart;
	protected Image ImitateButton_restart
	{
		get
		{
			if(_imitateButton_restart == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/$ImitateButton_restart");
				_imitateButton_restart = t.GetComponent<Image>();
			}
			return _imitateButton_restart;
		}
	}

	private Image _imitateButton_rating;
	protected Image ImitateButton_rating
	{
		get
		{
			if(_imitateButton_rating == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/$ImitateButton_rating");
				_imitateButton_rating = t.GetComponent<Image>();
			}
			return _imitateButton_rating;
		}
	}

	private Image _imitateButton_return;
	protected Image ImitateButton_return
	{
		get
		{
			if(_imitateButton_return == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/$ImitateButton_return");
				_imitateButton_return = t.GetComponent<Image>();
			}
			return _imitateButton_return;
		}
	}

	private ImitateDetailItemBar _imitateDetailItemBar1;
	protected ImitateDetailItemBar ImitateDetailItemBar1
	{
		get
		{
			if(_imitateDetailItemBar1 == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/Data/$ImitateDetailItemBar1");
				_imitateDetailItemBar1 = t.GetComponent<ImitateDetailItemBar>();
			}
			return _imitateDetailItemBar1;
		}
	}

	private ImitateDetailItemBar _imitateDetailItemBar2;
	protected ImitateDetailItemBar ImitateDetailItemBar2
	{
		get
		{
			if(_imitateDetailItemBar2 == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_score/Data/$ImitateDetailItemBar2");
				_imitateDetailItemBar2 = t.GetComponent<ImitateDetailItemBar>();
			}
			return _imitateDetailItemBar2;
		}
	}

	private RectTransform _tab_detail;
	protected RectTransform Tab_detail
	{
		get
		{
			if(_tab_detail == null)
			{
				var t = ElementUtils.FindByPath(transform, "$tab_detail");
				_tab_detail = t.GetComponent<RectTransform>();
			}
			return _tab_detail;
		}
	}

}
