using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class ImitateReadyPage : Page
{
	private Text _label_title;
	protected Text Label_title
	{
		get
		{
			if(_label_title == null)
			{
				var t = ElementUtils.FindByPath(transform, "Image/$label_title");
				_label_title = t.GetComponent<Text>();
			}
			return _label_title;
		}
	}

	private RawImage _rawImage_origin;
	protected RawImage RawImage_origin
	{
		get
		{
			if(_rawImage_origin == null)
			{
				var t = ElementUtils.FindByPath(transform, "$rawImage_origin");
				_rawImage_origin = t.GetComponent<RawImage>();
			}
			return _rawImage_origin;
		}
	}

	private Scrollbar _scrollbar;
	protected Scrollbar Scrollbar
	{
		get
		{
			if(_scrollbar == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Scrollbar");
				_scrollbar = t.GetComponent<Scrollbar>();
			}
			return _scrollbar;
		}
	}

	private Text _text_countdown;
	protected Text Text_countdown
	{
		get
		{
			if(_text_countdown == null)
			{
				var t = ElementUtils.FindByPath(transform, "image_countdown/$Text_countdown");
				_text_countdown = t.GetComponent<Text>();
			}
			return _text_countdown;
		}
	}

}
