using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class ImitateRankRow : MonoBehaviour
{
	private Image _image_frame;
	protected Image Image_frame
	{
		get
		{
			if(_image_frame == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Image_frame");
				_image_frame = t.GetComponent<Image>();
			}
			return _image_frame;
		}
	}

	private Image _image_huangguan;
	protected Image Image_huangguan
	{
		get
		{
			if(_image_huangguan == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Image_huangguan");
				_image_huangguan = t.GetComponent<Image>();
			}
			return _image_huangguan;
		}
	}

	private Image _image_icon;
	protected Image Image_icon
	{
		get
		{
			if(_image_icon == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Image_icon");
				_image_icon = t.GetComponent<Image>();
			}
			return _image_icon;
		}
	}

	private Text _text_name;
	protected Text Text_name
	{
		get
		{
			if(_text_name == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Text_name");
				_text_name = t.GetComponent<Text>();
			}
			return _text_name;
		}
	}

	private Text _text_dec;
	protected Text Text_dec
	{
		get
		{
			if(_text_dec == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Text_dec");
				_text_dec = t.GetComponent<Text>();
			}
			return _text_dec;
		}
	}

	private Text _text_score;
	protected Text Text_score
	{
		get
		{
			if(_text_score == null)
			{
				var t = ElementUtils.FindByPath(transform, "Image_scorebg/$Text_score");
				_text_score = t.GetComponent<Text>();
			}
			return _text_score;
		}
	}

	private Text _text_sort;
	protected Text Text_sort
	{
		get
		{
			if(_text_sort == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Text_sort");
				_text_sort = t.GetComponent<Text>();
			}
			return _text_sort;
		}
	}

}
