using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class ImitateDialogFloating : Floating
{
	private Text _test_content;
	protected Text Test_content
	{
		get
		{
			if(_test_content == null)
			{
				var t = ElementUtils.FindByPath(transform, "content/bg/$test_content");
				_test_content = t.GetComponent<Text>();
			}
			return _test_content;
		}
	}

}
