using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class ImitateDetailItemBar : MonoBehaviour
{
	private Text _text_name;
	protected Text Text_name
	{
		get
		{
			if(_text_name == null)
			{
				var t = ElementUtils.FindByPath(transform, "$text_name");
				_text_name = t.GetComponent<Text>();
			}
			return _text_name;
		}
	}

	private Scrollbar _scrollbar_progress;
	protected Scrollbar Scrollbar_progress
	{
		get
		{
			if(_scrollbar_progress == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Scrollbar_progress");
				_scrollbar_progress = t.GetComponent<Scrollbar>();
			}
			return _scrollbar_progress;
		}
	}

	private Text _text_percent;
	protected Text Text_percent
	{
		get
		{
			if(_text_percent == null)
			{
				var t = ElementUtils.FindByPath(transform, "$text_percent");
				_text_percent = t.GetComponent<Text>();
			}
			return _text_percent;
		}
	}

}
