using UnityEngine;
using UnityEngine.UI;
using System;

// This file was auto generated by ElementSystem
public partial class Scrollbar : MonoBehaviour
{
	private Image _image_fg;
	protected Image Image_fg
	{
		get
		{
			if(_image_fg == null)
			{
				var t = ElementUtils.FindByPath(transform, "$Image_fg");
				_image_fg = t.GetComponent<Image>();
			}
			return _image_fg;
		}
	}

}
